[package]
name = "pomodoro-platform"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
directories.workspace = true
pomodoro-core = { path = "../pomodoro-core" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
fs4 = "1.1.0"
same-file = "1.0.6"
tempfile = "3.26.0"

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
rustix.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
fs4 = "1.1.0"
same-file = "1.0.6"
windows-sys = { version = "0.61.2", features = ["Win32_Storage_FileSystem"] }

[lints]
workspace = true
