[package]
name = "pomodoro-platform"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
directories.workspace = true
pomodoro-core = { path = "../pomodoro-core" }
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
rustix.workspace = true

[target.'cfg(target_os = "linux")'.dev-dependencies]
tempfile = "3.26.0"

[lints]
workspace = true
